### ISSUE TITLE
The engine "yarn" is incompatible with this module

### ISSUE THREAD

**Issue by christopheschwyzer** [liorbd/react-basic-scroll#4]
When I try to install the module with `yarn` I get the following error. With `npm` it works fine.

```
error react-basic-scroll@1.1.0: The engine "yarn" is incompatible with this module. Expected version "YARN NO LONGER USED - use npm instead.". Got "1.17.3"
error Found incompatible module.
```

## Steps to reproduce
- Run install script `yarn add react-basic-scroll`

**Comment by liorbd** [comment]
@christopheschwyzer Thanks for opening this issue!
I fixed that and published a new version.
```yarn add react-basic-scroll``` is now working.

**Comment by christopheschwyzer** [comment]
Great. Thank you!
